"""Menu item type and vegetarian

Revision ID: 4f4152de297c
Revises: 44f390ff20b5
Create Date: 2022-02-27 13:10:01.739096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4152de297c'
down_revision = '44f390ff20b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_item', sa.Column('type', sa.Enum('STARTER', 'ENTREE', 'DESSERT', name='menuitemtype'), nullable=True))
    op.add_column('menu_item', sa.Column('vegetarian', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_item', 'vegetarian')
    op.drop_column('menu_item', 'type')
    # ### end Alembic commands ###
